In [1]:
import open3d as o3d
print(o3d.__version__)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
0.17.0


## Creating a Empty Mesh

In [4]:
mesh = o3d.geometry.TriangleMesh()
mesh

TriangleMesh with 0 points and 0 triangles.

## Loading Mesh, Creating Instance(Knot_mesh), Printing Vertices and Trainges

In [12]:
import numpy as np
print("Testing mesh in Open3D...")
armadillo_mesh = o3d.data.ArmadilloMesh()
mesh = o3d.io.read_triangle_mesh(armadillo_mesh.path)

knot_mesh = o3d.data.KnotMesh() # creating a instance like previous did
mesh = o3d.io.read_triangle_mesh(knot_mesh.path)
print(mesh)
print('Vertices:')
print(np.asarray(mesh.vertices))
print('Triangles:')
print(np.asarray(mesh.triangles))

Testing mesh in Open3D...
TriangleMesh with 1440 points and 2880 triangles.
Vertices:
[[  4.51268387  28.68865967 -76.55680847]
 [  7.63622284  35.52046967 -69.78063965]
 [  6.21986008  44.22465134 -64.82303619]
 ...
 [-22.12651634  31.28466606 -87.37570953]
 [-13.91188431  25.4865818  -86.25827026]
 [ -5.27768707  23.36245346 -81.43279266]]
Triangles:
[[   0   12   13]
 [   0   13    1]
 [   1   13   14]
 ...
 [1438   11 1439]
 [1439   11    0]
 [1439    0 1428]]


## Visulize a 3D mesh ==> Knot Mesh

In [34]:
knot_mesh = o3d.data.KnotMesh() # creating a instance like previous did
mesh = o3d.io.read_triangle_mesh(knot_mesh.path)

print("Try to render a mesh with normals (exist: " +
      str(mesh.has_vertex_normals()) + ") and colors (exist: " +
      str(mesh.has_vertex_colors()) + ")")
o3d.visualization.draw_geometries([mesh])
print("A mesh with no normals and no colors does not look good.")

Try to render a mesh with normals (exist: False) and colors (exist: False)
A mesh with no normals and no colors does not look good.


## Visulize a 3D mesh ==> Armadillo Mesh

In [25]:
import numpy as np
print("Testing mesh in Open3D...")
armadillo_mesh = o3d.data.ArmadilloMesh()
mesh = o3d.io.read_triangle_mesh(armadillo_mesh.path)

print("Try to render a mesh with normals (exist: " +
      str(mesh.has_vertex_normals()) + ") and colors (exist: " +
      str(mesh.has_vertex_colors()) + ")")
o3d.visualization.draw_geometries([mesh])
print("A mesh with no normals and no colors does not look good.")

Testing mesh in Open3D...
Try to render a mesh with normals (exist: False) and colors (exist: False)
A mesh with no normals and no colors does not look good.


## Surface Normal Estimation

In [36]:
print("Computing normal and rendering it.")
mesh.compute_vertex_normals()
print(np.asarray(mesh.triangle_normals))
o3d.visualization.draw_geometries([mesh])

Computing normal and rendering it.
[[ 0.79164373 -0.53951444  0.28674793]
 [ 0.8319824  -0.53303008  0.15389681]
 [ 0.83488162 -0.09250101  0.54260136]
 ...
 [ 0.16269924 -0.76215917 -0.6266118 ]
 [ 0.52755226 -0.83707495 -0.14489352]
 [ 0.56778973 -0.76467734 -0.30476777]]
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.


## Conveting the Mesh to Point Cloud ( Mesh ==> PCD )

In [29]:
import open3d as o3d

# Assuming you already have the mesh loaded
# mesh = o3d.io.read_triangle_mesh("your_mesh.obj")

# Sample points uniformly from the mesh surface (e.g., 5000 points)
point_cloud = mesh.sample_points_uniformly(number_of_points = 5000)

# Visualize the point cloud
o3d.visualization.draw_geometries([point_cloud])

## For Poisson Disk Sampling of PCD

In [30]:
point_cloud = mesh.sample_points_poisson_disk(number_of_points=5000)
o3d.visualization.draw_geometries([point_cloud])

## Crop mesh

## Croping mesh without normals

In [62]:
import copy 
print("We make a partial mesh of only the first half triangles.")
mesh1 = copy.deepcopy(mesh)
# bellow code is used ==> for the mesh
mesh1.triangles = o3d.utility.Vector3iVector(
    np.asarray(mesh1.triangles)[:len(mesh1.triangles) // 2, :])
o3d.visualization.draw_geometries([mesh1])

We make a partial mesh of only the first half triangles.


## Croping mesh normals

In [63]:
# bellow code is used => for the normal mesh (if we direct execute this then it is ohk)
mesh1.triangle_normals = o3d.utility.Vector3dVector(
    np.asarray(mesh1.triangle_normals)[:len(mesh1.triangle_normals) // 2, :])
print(mesh1.triangles)
o3d.visualization.draw_geometries([mesh1])

std::vector<Eigen::Vector3i> with 1440 elements.
Use numpy.asarray() to access data.


## Paint mesh

In [64]:
print("Painting the mesh")
mesh1.paint_uniform_color([1, 0.706, 0]) ## (R,G,B) ==> adjust the colors 
o3d.visualization.draw_geometries([mesh1])

Painting the mesh


## Mesh Properties ==> Manullay Fn is made for o3dtut 

In [3]:
import open3d as o3d
import numpy as np

# Helper function to visualize edges as LineSet
def edges_to_lineset(mesh, edges, color):
    """Convert edges to a LineSet with a specified color."""
    line_set = o3d.geometry.LineSet()
    line_set.points = mesh.vertices
    line_set.lines = o3d.utility.Vector2iVector(edges)
    line_set.paint_uniform_color(color)
    return line_set

# Function to generate a non-manifold edge mesh
def get_non_manifold_edge_mesh():
    """Creates a mesh with non-manifold edges."""
    mesh = o3d.geometry.TriangleMesh()
    vertices = np.array([
        [0, 0, 0], [1, 0, 0], [0.5, 1, 0], [0.5, 0.5, 1]
    ])
    triangles = np.array([
        [0, 1, 2], [0, 1, 3], [1, 2, 3], [0, 2, 3]
    ])
    mesh.vertices = o3d.utility.Vector3dVector(vertices)
    mesh.triangles = o3d.utility.Vector3iVector(triangles)
    return mesh

# Function to generate a non-manifold vertex mesh
def get_non_manifold_vertex_mesh():
    """Creates a mesh with non-manifold vertices."""
    mesh = o3d.geometry.TriangleMesh()
    vertices = np.array([
        [0, 0, 0], [1, 0, 0], [0.5, 1, 0], 
        [0.5, 0.5, 1], [0.5, 0.5, -1]
    ])
    triangles = np.array([
        [0, 1, 2], [0, 1, 3], [1, 2, 3], [0, 2, 3], 
        [0, 1, 4], [1, 2, 4]
    ])
    mesh.vertices = o3d.utility.Vector3dVector(vertices)
    mesh.triangles = o3d.utility.Vector3iVector(triangles)
    return mesh

# Function to generate an open box mesh
def get_open_box_mesh():
    """Creates an open box mesh (one face removed)."""
    mesh = o3d.geometry.TriangleMesh.create_box(width=1.0, height=1.0, depth=1.0)
    mesh.remove_triangles_by_index([4, 5])  # Remove one face to create an opening
    return mesh

# Function to generate intersecting box meshes
def get_intersecting_boxes_mesh():
    """Creates two intersecting boxes."""
    box1 = o3d.geometry.TriangleMesh.create_box(width=1.0, height=1.0, depth=1.0)
    box2 = o3d.geometry.TriangleMesh.create_box(width=1.0, height=1.0, depth=1.0)
    box2.translate((0.5, 0.5, 0.5))  # Move the second box to cause intersection
    mesh = box1 + box2
    return mesh

# Function to check mesh properties
def check_properties(name, mesh):
    mesh.compute_vertex_normals()

    edge_manifold = mesh.is_edge_manifold(allow_boundary_edges=True)
    edge_manifold_boundary = mesh.is_edge_manifold(allow_boundary_edges=False)
    vertex_manifold = mesh.is_vertex_manifold()
    self_intersecting = mesh.is_self_intersecting()
    watertight = mesh.is_watertight()
    orientable = mesh.is_orientable()

    print(name)
    print(f"  edge_manifold:          {edge_manifold}")
    print(f"  edge_manifold_boundary: {edge_manifold_boundary}")
    print(f"  vertex_manifold:        {vertex_manifold}")
    print(f"  self_intersecting:      {self_intersecting}")
    print(f"  watertight:             {watertight}")
    print(f"  orientable:             {orientable}")

    geoms = [mesh]
    
    # Highlight non-manifold edges
    if not edge_manifold:
        edges = mesh.get_non_manifold_edges(allow_boundary_edges=True)
        geoms.append(edges_to_lineset(mesh, edges, (1, 0, 0)))  # Red color

    if not edge_manifold_boundary:
        edges = mesh.get_non_manifold_edges(allow_boundary_edges=False)
        geoms.append(edges_to_lineset(mesh, edges, (0, 1, 0)))  # Green color

    # Highlight non-manifold vertices
    if not vertex_manifold:
        verts = np.asarray(mesh.get_non_manifold_vertices())
        pcl = o3d.geometry.PointCloud(
            points=o3d.utility.Vector3dVector(np.asarray(mesh.vertices)[verts])
        )
        pcl.paint_uniform_color((0, 0, 1))  # Blue color
        geoms.append(pcl)

    # Highlight self-intersecting triangles
    if self_intersecting:
        intersecting_triangles = np.asarray(mesh.get_self_intersecting_triangles())
        if len(intersecting_triangles) > 0:  # Prevent IndexError
            intersecting_triangles = intersecting_triangles[0:1]
            intersecting_triangles = np.unique(intersecting_triangles)
            print("  # Visualizing self-intersecting triangles")
            triangles = np.asarray(mesh.triangles)[intersecting_triangles]
            edges = [
                np.vstack((triangles[:, i], triangles[:, j]))
                for i, j in [(0, 1), (1, 2), (2, 0)]
            ]
            edges = np.hstack(edges).T
            edges = o3d.utility.Vector2iVector(edges)
            geoms.append(edges_to_lineset(mesh, edges, (1, 0, 1)))  # Purple color

    o3d.visualization.draw_geometries(geoms, mesh_show_back_face=True)

KnotMesh
  edge_manifold:          True
  edge_manifold_boundary: True
  vertex_manifold:        True
  self_intersecting:      False
  watertight:             True
  orientable:             True
Mobius
  edge_manifold:          True
  edge_manifold_boundary: False
  vertex_manifold:        True
  self_intersecting:      False
  watertight:             False
  orientable:             False
non-manifold edge
  edge_manifold:          True
  edge_manifold_boundary: True
  vertex_manifold:        True
  self_intersecting:      False
  watertight:             True
  orientable:             True
non-manifold vertex
  edge_manifold:          False
  edge_manifold_boundary: False
  vertex_manifold:        True
  self_intersecting:      False
  watertight:             False
  orientable:             True
open box
  edge_manifold:          True
  edge_manifold_boundary: False
  vertex_manifold:        True
  self_intersecting:      False
  watertight:             False
  orientable:            

In [ ]:
# Load Knot Mesh
knot_mesh_data = o3d.data.KnotMesh()
knot_mesh = o3d.io.read_triangle_mesh(knot_mesh_data.path)

# Check properties of various meshes
check_properties('KnotMesh', knot_mesh)
check_properties('Mobius', o3d.geometry.TriangleMesh.create_mobius(twists=1))
check_properties("non-manifold edge", get_non_manifold_edge_mesh())
check_properties("non-manifold vertex", get_non_manifold_vertex_mesh())
check_properties("open box", get_open_box_mesh())
check_properties("intersecting_boxes", get_intersecting_boxes_mesh())

## Removes non-manifold edges

In [31]:

    mesh = o3d.geometry.TriangleMesh()
    vertices = np.array([
        [0, 0, 0], [1, 0, 0], [0.5, 1, 0], [0.5, 0.5, 1]
    ])
    triangles = np.array([
        [0, 1, 2], [0, 1, 3], [1, 2, 3], [0, 2, 3]
    ])
    mesh.vertices = o3d.utility.Vector3dVector(vertices)
    mesh.triangles = o3d.utility.Vector3iVector(triangles)
mesh.compute_vertex_normals()
mesh.remove_non_manifold_edges()  # Removes non-manifold edges
o3d.visualization.draw_geometries([mesh])

## Mesh Filters

# 1. Average Filter

In [5]:
## Creating ==> Noise Knot Mesh
print('create noisy mesh')
knot_mesh = o3d.data.KnotMesh()
mesh_in = o3d.io.read_triangle_mesh(knot_mesh.path)
vertices = np.asarray(mesh_in.vertices)
noise = 5
vertices += np.random.uniform(0, noise, size=vertices.shape)
mesh_in.vertices = o3d.utility.Vector3dVector(vertices)
mesh_in.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh_in])

create noisy mesh


In [75]:
print('filter with average with 1 iteration')
mesh_out = mesh_in.filter_smooth_simple(number_of_iterations=1)
mesh_out.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh_out])

filter with average with 1 iteration


In [82]:
print('filter with average with 5 iterations')
mesh_out = mesh_in.filter_smooth_simple(number_of_iterations=5)
mesh_out.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh_out])

filter with average with 5 iterations


## 2. Laplacian Filter

In [9]:
print('filter with Laplacian with 10 iterations')
mesh_out = mesh_in.filter_smooth_laplacian(number_of_iterations=10)
mesh_out.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh_out])

filter with Laplacian with 10 iterations


In [11]:
print('filter with Laplacian with 50 iterations')
mesh_out = mesh_in.filter_smooth_laplacian(number_of_iterations=50)
mesh_out.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh_out])

filter with Laplacian with 50 iterations


## 3. Taubin filter

In [13]:
# Apply Taubin smoothing with 10 iterations
print('Filter with Taubin with 10 iterations')
mesh_out = mesh_in.filter_smooth_taubin(number_of_iterations=10)
mesh_out.compute_vertex_normals()  # Recompute normals for rendering
o3d.visualization.draw_geometries([mesh_out])

filter with Taubin with 10 iterations


In [15]:
# Apply Taubin smoothing with 100 iterations
print('Filter with Taubin with 100 iterations')
mesh_out = mesh_in.filter_smooth_taubin(number_of_iterations=100)
mesh_out.compute_vertex_normals()  # Recompute normals for rendering
o3d.visualization.draw_geometries([mesh_out])

Filter with Taubin with 100 iterations


## Sampling

## 1. Uniform Sampling

In [4]:
# mesh ==> Sphere
mesh = o3d.geometry.TriangleMesh.create_sphere()
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh])
pcd = mesh.sample_points_uniformly(number_of_points=500)
o3d.visualization.draw_geometries([pcd])

In [5]:
# Mesh ==> BunnyMesh
bunny = o3d.data.BunnyMesh()
mesh = o3d.io.read_triangle_mesh(bunny.path)
mesh.compute_vertex_normals()

o3d.visualization.draw_geometries([mesh])
pcd = mesh.sample_points_uniformly(number_of_points=500)
o3d.visualization.draw_geometries([pcd])

##  2. Poisson Disk Sampling 

## Without pcl(without custom initalization)                [ init_factor*number_of_points ]

In [14]:
mesh = o3d.geometry.TriangleMesh.create_sphere()
pcd = mesh.sample_points_poisson_disk(number_of_points=500, init_factor=5)
o3d.visualization.draw_geometries([pcd])

In [16]:
print('init_factor * number_if_points and it reduce upto 500 poisson distribution')
print(pcd)

init_factor * number_if_points and it reduce upto 500 poisson distribution
PointCloud with 500 points.


## with pcl(with custom initalization)

In [ ]:
# Create a sphere mesh
mesh = o3d.geometry.TriangleMesh.create_sphere()

# Step 1: Generate an initial point cloud using uniform sampling
initial_pcd = mesh.sample_points_uniformly(number_of_points=2500)

# Step 2: Use this initial point cloud for Poisson Disk Sampling
pcd_pcl = mesh.sample_points_poisson_disk(number_of_points=500, pcl=initial_pcd)

# Visualize the sampled point cloud
o3d.visualization.draw_geometries([pcd_pcl])

In [18]:
print(initial_pcd)
print(pcd_pcl)

PointCloud with 2500 points.
PointCloud with 500 points.


## Mesh subdivision

## 1. Mid-Point Subdivision

In [28]:
# Create a simple box mesh
mesh = o3d.geometry.TriangleMesh.create_box()
mesh.compute_vertex_normals()
print(f'Original Mesh: {len(mesh.vertices)} vertices, {len(mesh.triangles)} triangles')

# Visualize before subdivision
o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True)

# Apply midpoint subdivision
mesh = mesh.subdivide_midpoint(number_of_iterations=1)
print(f'After Subdivision: {len(mesh.vertices)} vertices, {len(mesh.triangles)} triangles')

# Visualize after subdiknot_mesh = o3d.data.KnotMesh()
mesh = o3d.io.read_triangle_mesh(knot_mesh.path)
mesh = mesh.subdivide_loop(number_of_iterations=1)vision
o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True)

Original Mesh: 8 vertices, 12 triangles
After Subdivision: 26 vertices, 48 triangles


In [48]:
knot_mesh = o3d.data.KnotMesh()
mesh = o3d.io.read_triangle_mesh(knot_mesh.path)

mesh = o3d.io.read_triangle_mesh(knot_mesh.path)
mesh.compute_vertex_normals()
mesh = mesh.subdivide_loop(number_of_iterations=1)
o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True)

## 2. Loop Subdivision

## Sphere mesh using loop subdivision

In [50]:
mesh = o3d.geometry.TriangleMesh.create_sphere()
mesh.compute_vertex_normals()
print(
    f'The mesh has {len(mesh.vertices)} vertices and {len(mesh.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True)
mesh = mesh.subdivide_loop(number_of_iterations=2)
print(
    f'After subdivision it has {len(mesh.vertices)} vertices and {len(mesh.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True)

The mesh has 762 vertices and 1520 triangles
After subdivision it has 12162 vertices and 24320 triangles


## Knot Mesh using Loop Division

In [52]:
knot_mesh = o3d.data.KnotMesh()
mesh = o3d.io.read_triangle_mesh(knot_mesh.path)
mesh.compute_vertex_normals()
print(
    f'The mesh has {len(mesh.vertices)} vertices and {len(mesh.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True)
mesh = mesh.subdivide_loop(number_of_iterations=1)
print(
    f'After subdivision it has {len(mesh.vertices)} vertices and {len(mesh.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True)

The mesh has 1440 vertices and 2880 triangles
After subdivision it has 5760 vertices and 11520 triangles


## Mesh Simplification

## Vertex clustering

In [3]:
bunny = o3d.data.BunnyMesh()
mesh_in = o3d.io.read_triangle_mesh(bunny.path)
mesh_in.compute_vertex_normals()

print(
    f'Input mesh has {len(mesh_in.vertices)} vertices and {len(mesh_in.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh_in])

Input mesh has 35947 vertices and 69451 triangles


In [4]:
voxel_size = max(mesh_in.get_max_bound() - mesh_in.get_min_bound()) / 32
print(f'voxel_size = {voxel_size:e}')
mesh_smp = mesh_in.simplify_vertex_clustering(
    voxel_size=voxel_size,
    contraction=o3d.geometry.SimplificationContraction.Average)
print(
    f'Simplified mesh has {len(mesh_smp.vertices)} vertices and {len(mesh_smp.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh_smp])

voxel_size = 4.865594e-03
Simplified mesh has 3222 vertices and 6454 triangles


In [5]:
voxel_size = max(mesh_in.get_max_bound() - mesh_in.get_min_bound()) / 16
print(f'voxel_size = {voxel_size:e}')
mesh_smp = mesh_in.simplify_vertex_clustering(
    voxel_size=voxel_size,
    contraction=o3d.geometry.SimplificationContraction.Average)
print(
    f'Simplified mesh has {len(mesh_smp.vertices)} vertices and {len(mesh_smp.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh_smp])

voxel_size = 9.731187e-03
Simplified mesh has 845 vertices and 1724 triangles


## Mesh decimation

In [17]:
mesh_smp = mesh_in.simplify_quadric_decimation(target_number_of_triangles=6500)
print(
    f'Simplified mesh has {len(mesh_smp.vertices)} vertices and {len(mesh_smp.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh_smp])

Simplified mesh has 4405 vertices and 6499 triangles


In [32]:
mesh_smp = mesh_in.simplify_quadric_decimation(target_number_of_triangles=1700)
print(
    f'Simplified mesh has {len(mesh_smp.vertices)} vertices and {len(mesh_smp.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh_smp])

Simplified mesh has 1978 vertices and 1700 triangles


## Connected components

In [33]:
## Adding a small samll cube in the mesh 
import numpy as np
print("Generate data")
bunny = o3d.data.BunnyMesh()
mesh = o3d.io.read_triangle_mesh(bunny.path)
mesh.compute_vertex_normals()

mesh = mesh.subdivide_midpoint(number_of_iterations=2)
vert = np.asarray(mesh.vertices)
min_vert, max_vert = vert.min(axis=0), vert.max(axis=0)
for _ in range(30):
    cube = o3d.geometry.TriangleMesh.create_box()
    cube.scale(0.005, center=cube.get_center())
    cube.translate(
        (
            np.random.uniform(min_vert[0], max_vert[0]),
            np.random.uniform(min_vert[1], max_vert[1]),
            np.random.uniform(min_vert[2], max_vert[2]),
        ),
        relative=False,
    )
    mesh += cube
mesh.compute_vertex_normals()
print("Show input mesh")
o3d.visualization.draw_geometries([mesh])

Generate data
Show input mesh


In [56]:
## Cluster connected triangles
print("Cluster connected triangles")
with o3d.utility.VerbosityContextManager(
        o3d.utility.VerbosityLevel.Debug) as cm:
    triangle_clusters, cluster_n_triangles, cluster_area = (
        mesh.cluster_connected_triangles())
triangle_clusters = np.asarray(triangle_clusters)
cluster_n_triangles = np.asarray(cluster_n_triangles)
cluster_area = np.asarray(cluster_area)

Cluster connected triangles
[Open3D DEBUG] [ClusterConnectedTriangles] Compute triangle adjacency
[Open3D DEBUG] [ClusterConnectedTriangles] Done computing triangle adjacency
[Open3D DEBUG] [ClusterConnectedTriangles] Done clustering, #clusters=31


In [43]:
print("An array where each triangle is assigned a cluster ID.(Index)")
print(triangle_clusters)
print("An array that holds the number of triangles for each cluster.")
print(cluster_n_triangles)
print("An array containing the surface area of each cluster.")
print(cluster_area)

An array where each triangle is assigned a cluster ID.(Index)
[ 0  0  0 ... 30 30 30]
An array that holds the number of triangles for each cluster.
[1111216      12      12      12      12      12      12      12      12
      12      12      12      12      12      12      12      12      12
      12      12      12      12      12      12      12      12      12
      12      12      12      12]
An array containing the surface area of each cluster.
[0.05712878 0.00015    0.00015    0.00015    0.00015    0.00015
 0.00015    0.00015    0.00015    0.00015    0.00015    0.00015
 0.00015    0.00015    0.00015    0.00015    0.00015    0.00015
 0.00015    0.00015    0.00015    0.00015    0.00015    0.00015
 0.00015    0.00015    0.00015    0.00015    0.00015    0.00015
 0.00015   ]


In [63]:
import copy
print("Show mesh with small clusters removed") # ---> Remove the Small cube
mesh_0 = copy.deepcopy(mesh)
triangles_to_remove = cluster_n_triangles[triangle_clusters] < 100
print(triangles_to_remove)
mesh_0.remove_triangles_by_mask(triangles_to_remove)
o3d.visualization.draw_geometries([mesh_0])

Show mesh with small clusters removed
[False False False ...  True  True  True]


In [66]:
import copy
print("Show mesh with Large clusters removed")    #  ==> Remove the large cluster i.e Bunny
mesh_0 = copy.deepcopy(mesh)
triangles_to_remove = cluster_n_triangles[triangle_clusters] > 100
print(triangles_to_remove)
mesh_0.remove_triangles_by_mask(triangles_to_remove)
o3d.visualization.draw_geometries([mesh_0])

Show mesh with small clusters removed
[ True  True  True ... False False False]


In [67]:
print("Show largest cluster")   ##  ==> >showing the lage cluster i.e bunny
mesh_1 = copy.deepcopy(mesh)
largest_cluster_idx = cluster_n_triangles.argmax()
triangles_to_remove = triangle_clusters != largest_cluster_idx
mesh_1.remove_triangles_by_mask(triangles_to_remove)
o3d.visualization.draw_geometries([mesh_1])

Show largest cluster
