In [1]:
import open3d as o3d
print(o3d.__version__)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
0.17.0


## Without Downsampling With Path 

In [2]:
# Local dataset ==> Bunny dataset

import open3d as o3d
import numpy as np

# Load the point cloud from a PLY file
pcd = o3d.io.read_point_cloud("C:/Users/sumit/Downloads/bunny/bunny/reconstruction/bun_zipper_res2.ply")

# Print the point cloud and its points as a NumPy array
print(pcd)
print(np.asarray(pcd.points))

# Set better camera parameters to ensure the point cloud is visible
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(pcd)

# Adjust camera parameters manually to ensure a good view of the point cloud
view_control = vis.get_view_control()
view_control.set_zoom(0.5)  # Zoom out a bit if the cloud is small
view_control.set_front([1.0, -1.0, 0.0])  # Front direction
view_control.set_lookat([0.0, 0.0, 0.0])  # Look at the center of the point cloud
view_control.set_up([0.0, 0.0, 1.0])  # Up direction

# Run the visualization loop
vis.run()
vis.destroy_window()

PointCloud with 8171 points.
[[-0.036872    0.127727    0.00440925]
 [-0.0453607   0.128854    0.00114541]
 [-0.0690069   0.151612    0.0366018 ]
 ...
 [-0.0643695   0.149877   -0.0298747 ]
 [-0.0528961   0.143026   -0.00045591]
 [-0.0318636   0.155275   -0.00893878]]


## Downsampling

In [3]:
import open3d as o3d
import numpy as np

# Load the point cloud from a PLY file
pcd = o3d.io.read_point_cloud("C:/Users/sumit/Downloads/ours_lobby/lobby.ply")

# Print the point cloud and its points as a NumPy array
print(pcd)
print(np.asarray(pcd.points))

# Downsample the point cloud with a voxel size of 0.05 (you can change this value)
downpcd = pcd.voxel_down_sample(voxel_size=0.1)

# Print the downsampled point cloud and its points
print("Downsampled PointCloud")
print(downpcd)
print(np.asarray(downpcd.points))

# Set better camera parameters to ensure the point cloud is visible
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(downpcd)  # Use the downsampled point cloud instead of the original one

# Adjust camera parameters manually to ensure a good view of the point cloud
view_control = vis.get_view_control()
view_control.set_zoom(0.5)  # Zoom out a bit if the cloud is small
view_control.set_front([1.0, -1.0, 0.0])  # Front direction
view_control.set_lookat([0.0, 0.0, 0.0])  # Look at the center of the point cloud
view_control.set_up([0.0, 0.0, 1.0])  # Up direction

# Run the visualization loop
vis.run()
vis.destroy_window()

PointCloud with 13872772 points.
[[-1.7607e+00 -2.9590e-01 -8.8833e-01]
 [-1.7609e+00 -2.9590e-01 -8.8770e-01]
 [-1.7607e+00 -2.9525e-01 -8.8770e-01]
 ...
 [ 9.0820e-02  5.1123e+00 -6.8202e+00]
 [-2.9297e-03  5.2178e+00 -6.8269e+00]
 [ 1.3184e-01  5.9160e+00 -7.0400e+00]]
Downsampled PointCloud
PointCloud with 44045 points.
[[-4.10837329e-01 -7.47546925e-01  2.50593137e+00]
 [ 4.08798794e-01  1.01183539e+00  2.18118511e+00]
 [ 7.94457653e-01  3.96696626e+00 -5.76617408e+00]
 ...
 [-7.23787200e-03  5.26033396e+00 -6.90834491e+00]
 [-4.19469222e-03  5.22365556e+00 -6.83718889e+00]
 [ 7.00878118e-03  5.23647647e+00 -6.84539412e+00]]


In [4]:
print("Recompute the normal of the downsampled point cloud")
downpcd.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
o3d.visualization.draw_geometries([downpcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024],
                                  point_show_normal=True)

Recompute the normal of the downsampled point cloud


## Thinter Code ==> Start to Normalize Estimate Vectoer

In [5]:
import open3d as o3d
import numpy as np
import tkinter as tk
from tkinter import filedialog

# 1. Open a file dialog to choose the PLY file
root = tk.Tk()
root.withdraw()  # Hide the root window (we just want the file dialog)
file_path = filedialog.askopenfilename(title="Select a Point Cloud file", filetypes=[("PLY Files", "*.ply")])

# Check if a file was selected
if not file_path:
    print("No file selected.")
else:
    # 2. Load the point cloud from the selected PLY file
    pcd = o3d.io.read_point_cloud(file_path)

    # Print the point cloud and its points as a NumPy array
    print(pcd)
    print(np.asarray(pcd.points))

    # 3. Downsample the point cloud with a voxel size of 0.1 (you can change this value)
    downpcd = pcd.voxel_down_sample(voxel_size=0.1)

    # Print the downsampled point cloud and its points
    print("Downsampled PointCloud")
    print(downpcd)
    print(np.asarray(downpcd.points))

    # 4. Set better camera parameters to ensure the point cloud is visible
    vis = o3d.visualization.Visualizer()
    vis.create_window()
    vis.add_geometry(downpcd)  # Use the downsampled point cloud instead of the original one

    # Adjust camera parameters manually to ensure a good view of the point cloud
    view_control = vis.get_view_control()
    view_control.set_zoom(0.5)  # Zoom out a bit if the cloud is small
    view_control.set_front([1.0, -1.0, 0.0])  # Front direction
    view_control.set_lookat([0.0, 0.0, 0.0])  # Look at the center of the point cloud
    view_control.set_up([0.0, 0.0, 1.0])  # Up direction

    # 5. Run the visualization loop
    vis.run()
    vis.destroy_window()

    # 6. Recompute the normal of the downsampled point cloud
    print("Recompute the normal of the downsampled point cloud")
    downpcd.estimate_normals(
        search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))

    # 7. Visualize the point cloud with normals
    o3d.visualization.draw_geometries([downpcd],
                                      zoom=0.3412,
                                      front=[0.4257, -0.2125, -0.8795],
                                      lookat=[2.6172, 2.0475, 1.532],
                                      up=[-0.0694, -0.9768, 0.2024],
                                      point_show_normal=True)


PointCloud with 137070 points.
[[1.48169196 1.47363091 0.40797529]
 [1.48068249 1.47503877 0.4229607 ]
 [1.48884368 1.49680889 0.43765184]
 ...
 [4.89285278 2.59598804 0.11020485]
 [4.70525026 2.66881609 0.09415986]
 [4.7298646  2.67439437 0.09585464]]
Downsampled PointCloud
PointCloud with 5821 points.
[[1.45172368 1.4681056  1.34715625]
 [2.66917062 2.26551142 0.68703064]
 [2.64643123 2.26801932 0.63902875]
 ...
 [5.01786831 2.57519335 0.09515126]
 [4.61031908 2.76111509 0.08790307]
 [4.77201831 3.05261537 0.05501766]]
Recompute the normal of the downsampled point cloud
